Feature/29
the-pool/the-pool-api pull request #34
Opened 2022-11-12 07:31 UTC by subroooo

## Motivation
- 과제 생성 api 생성

<br>

## Key Changes
- 과제 생성 및 createManyMapper 

<br>

## To Reviewers
- 과제 생성을 위해 필요한 최소 한의 요소만 들어간 api 입니다. 
- 이미지를 받는 작업은 이후 aws sdk를 붙이는 이슈를 만들어 작업 후에 진행하도록 하겠습니다.

2022-11-12 11:15 UTC, rrgks6221 reviewed
아직 컨벤션이나 아키텍처같은게 덜 잡힌 상태라 피드백이 많긴한데 모든 피드뱍 수용할 필요는 없습니다~~
@RokwonK 님 험께 의견 나눠봐여하는 부분레 멘션 했는데 의견 한번 주심 좋을거같아요

2022-11-12 11:15 UTC, rrgks6221 commented on src/common/common.ts
> +export const createManyMapper = <T>(obj: {
이 함수를 사용하는 목적이 createMany를 쉽게 이용할 수 있게 만드는 함수로 보입니다.
1. 길이가 0일때 빈배열을 리턴하는데 리턴값을 createMany method 에 넣었을때 일어나는 동작을 확인해볼 필요가 있을거같아요.
2. 여러개의 배열 중 길이가 다를 경우 error 을 뱉는데 이 부분 좀더 고도화 하면 좋을거같아요 지금 구조에선 nodeExcrptionFilter 에 잡힐텐데 메시지 형태가 불친절하여 디버깅하는데 좋지 읺을거란 생각이 들고 가장 베스트는 배열의 길이를 강제하는 타입을 만들게 돼면 컴파일 단계에서 잡을 수 있어서 런타임에서 에러를 throw 할 일이 없어집니다. 이 타입 강제는 저도 구현은 떠오르질 않네요.
3. common.js 의 함수들을 보면 데코레이터에 들어가는 함수, 테스트코드에 쓰이는 함수가 있는데 di 받아서 사용할 수 없거나 필요가 없는 함수들만 모여있습니다. 이 함수같은 경우에 그대로 import 하여 사용하면 강하게 결합돼 사용하는게 되어 하나의 클레스로 묶어서 di 받아서 사용하는 구조가 되면 좋을거같네요
4. 3번에서 테스트코드에 사용되는 함수도 test에 관련된 메서드를 모아놓은 클레스를 만들어 테스팅 모듈을 만들 때 프로바이더로 등록하는것도 고려해보면 좋을거같아요

2022-11-12 11:15 UTC, rrgks6221 commented on src/constants/enum.ts
> +}
```suggestion
// 과제물 난이도
export enum LessonLevelId {
  // 상
  Top = 1,
  // 중
  Middle = 2,
  // 하
  Bottom = 3,
}
```
처음 enum 또는 상수를 만들때부터 얘기했어야하긴 하는데 영어 네이밍으로 모든 형태를 표현할 수 없어서 주석을 다는데 이런 상수또한 마찬가지로 생각합니다 이런식으로 주석을 달았을 때 해당 파일에 들어가지 않아도 에디터에서 주석을 보여줄 수 있습니다. 다같이 한번 얘기해보면 좋을거같네요.
@RokwonK

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson.controller.spec.ts
> +      spyCreateLesson = jest.spyOn(lessonService, 'createLesson');
테스팅 모듈울 만들 때 구현체를 jest.fn() 으로 모의한 값이 들어가면서 자연스럽게 spy 가 될거같은데 spy 를 한번 더 해준 의도가 궁금하네요

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson.controller.spec.ts
> +        id: 1,
mock data 를 상수로 넣었을 때 이 경우에만 성공하는 테스팅이 될 수 있어서 저는 fakerjs 를 사용하는데 한번 고려해주심 좋을거같아요

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson.controller.ts
> +  @UseGuards(AuthGuard('jwt'))
1. jwt guard 를 쓸 때 @ApiBearerAuth 라는 데코레이터를 달아야 스웨거 환경에서 사용 가능합니다.
applyDecorator 를 사용하여 두개의 데코레이터를 합친 데코레이터를 만드는것도 방법이 될거같네요
2. example 로 만든 postModule 을 보면 보다 간결하게 표현한 방법이 있는데 한번 보시고 고려 부탁드릴게여

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/lesson/dtos/create-lesson.dto.ts
> +  @Length(1, 50)
maxLength 또는 minLength 를 상수로 관리하는것도 고려해볼 수 있을거같아요
지금은 한곳에서만 쓰이고있지만 더 많은 곳에서 사용할 수 있는 가능성이 있습니다
ex)
1. 해당 기능 테스트코드 구현 시 지금처럼 임의의 문자열을 넣었을 경우에 정책이 바뀌어 1000자로 올라간다거나 했을 때 해당 테스트는 깨질 수 있는데 상수로 만들어서 str.repeat(상수 + 1), fakerjs 의 faker.datatype.string(상수 + 1) 처럼 구현하면 수정없이 깨지지않는 테스트 코드 구현
2. 클라이언트는 이 타이틀의 최대 길이를 모르기 때문에 에러로 넘겨줄 때 사용할 수 있겠네요
3. swagger 문서에 사용 할 수 있겠네요

이렇게 경우가 많아졌을 때 한곳에서 관리하게 된다면 코드 중복을 줄이면서 수정에 용이한 코드가 될 수 있을거같아서 얘기해보명 좋을거같네여
@RokwonK

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/lesson/dtos/create-lesson.dto.ts
> +  hashtag: string[];
이 property도 클라이언트에게 받는 property같은데 pick으로 ApiProperty 데코레이터를 땡겨오지 않아서 swagger 문서에 안나타나지 않나요??

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/lesson/entities/lesson.entity.ts
> +import { Lesson as LessonModel } from '@prisma/client';
별칭을 사용한게 Post 모듈 보시고 한거같은데 그때 별칭을 사용한건 모델이라는걸 명시해주는 목적이 아니고 라우팅 테코레이터 Post 와 이름이 같아서 강제로 바꿔주려고 했던 의도입니다. 만약 Post Module 을 따라한거라면 그렇게 안하셔도 됩니다.
아님말구

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/lesson/entities/lesson.entity.ts
> +    example: 1,
Enum 을 만들었으면 적극적으로 사용하는 것도 좋겠네요 1이라는 값은 정책이 바뀐다면 수정대상이 되는데 관리를 안해줄 가능성이 높고 enum 은 수정할테니까요

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/lesson/entities/lesson.entity.ts
> +    required: true,
required true 라고 명시해주는것 아주 좋아요

혹시 모르시나 해서 알려드려요
ApiProperty 데코레이터를 사용하면 required는 기본으로 true 로 들어갑니다
반대로 기본값이 false 인 이름이 비슷한 데코레이터도 있으니 찾아보심 좋을듯 해요
이건 취향에 따라 선택하면 좋을듯해요

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/lesson/entities/lesson.entity.ts
> +    type: 'number',
```suggestion
```

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/lesson/entities/lesson.entity.ts
> +  levelId: number;
```suggestion
  levelId: LessonLevelId;
```
일반 상수가 아닌 Enum을 사용하는게 타입으로 쓸 수 있다는 점도 있을거같은데 적극 사용하면 좀 더 엄격하게 타입을 관리할 수 있을거같네여

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/lesson/entities/lesson.entity.ts
> +  @ApiProperty({
제목의 최대길이가 50 이라는 정보를 Length validation 에 걸려야만 클라이언트가 확이 할 수 있어서 추가되면 좋을거같아요

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/member/controllers/member.controller.ts
> +@Controller('api/members')
path 를 복수로 가져가면서 통일 해주려는 의도는 좋습니다
하지만 이미 배포된 api 대해서 path 같은 클라이언트가 수정할 일이 있는 수정에 대해서는 한번 공유해보고 수정하는게 좋을 듯 해요
만약 실 배포 환경에서 커뮤니케이션 없이 path 가 바뀐다면 해당 기능을 사용할 수 없게 되니까요

2022-11-12 11:15 UTC, rrgks6221 commented on src/types/type.ts
> +export type PrismaModel = 'user' | 'post' | 'member' | 'lesson';
잊지않고 추가해주시는거 너무 좋네요

2022-11-12 11:15 UTC, rrgks6221 commented on src/modules/member/entities/member.entity.ts
> +    description: 'member의 프로필 이미지',
url path 라는 정보도 있으면 어떨까싶네요
개인적으로 클라이언트에게 질문을 덜 받을수록 좋은 문서, api 를 만들었다고 생각합니다
물론 개인적인 생각입니다.

2022-11-13 06:21 UTC, subroooo commented on src/common/common.ts
> +export const createManyMapper = <T>(obj: {
1. 길이가 0일 때 리턴된 빈 배열의 동작은 craeteMany대상 테이블에 insert가 들어가지 않는 것으로 확인했습니다!!
2. 타입을 통해 2차원 배열의 각 요소의 길이를 맞추는 방식을 어제 저녁부터 지금까지 알아보았지만 좋은 방법을 찾지 못했습니다...
3. 여태 common 함수를 만들 때 각각의 역할을 구분하지 않고 common에 넣은 것 같네요 앞으로 신경쓰겠습니다! 
4. customValidate같은 경우 DTO layer 구현체에서 class-validator를 di받아 사용하지 않기 때문에(constructor가 없음) test 관련 메서드를 모은 클래스를 만들어도 testing module에서 di를 시켜줄 방법이 없습니다.
그러나 dto layer를 제외한 다른 layer에서 test를 작성할 때 test 관련 메서드를 모은 클래스를 DI받아 사용하는 것은 전적으로 동의합니다!

2022-11-13 06:33 UTC, subroooo commented on src/constants/enum.ts
> +}
enum이나 상수를 만들 때 영어로 네이밍을 하면서 설명이 부족하다는 생각을 했었는데 주석으로 부족한 영어 네이밍을 보충하는 방법 좋은 것 같습니다!

2022-11-13 06:57 UTC, subroooo commented on src/modules/lesson/controllers/lesson.controller.spec.ts
> +      spyCreateLesson = jest.spyOn(lessonService, 'createLesson');
테스트 모듈을 만들 때 구현체를 jest.fn()을 통해 만들어 모킹해주면 spy를 사용할 수 있다는 것을 자꾸 
까먹네요...

2022-11-13 07:18 UTC, subroooo commented on src/modules/lesson/controllers/lesson.controller.spec.ts
> +        id: 1,
오....mock data 를 상수로 넣었을 때, 넣어준 상수에 대해서만 성공하는 테스팅이 될 수 있다는 것을 생각 못했네요!
앞으로는 fakerjs를 사용하도록 하겠습니다.

2022-11-13 07:31 UTC, subroooo commented on src/modules/lesson/controllers/lesson.controller.ts
> +  @UseGuards(AuthGuard('jwt'))
@ApiBearerAuth 데코레이터를 사용해서 swagger 상에서 요청을 날릴 때 token을 받아올 수 있네요!!
추가하겠습니다!!
말씀해주신 것처럼 applyDecorator를 사용해 좀 더 간결하고 가독성있는 코드로 변경하겠습니다!

2022-11-13 07:45 UTC, subroooo commented on src/modules/lesson/dtos/create-lesson.dto.ts
> +  @Length(1, 50)
너무 좋은 생각입니다.
"많은 곳에서 사용되는 상수 > 변수로 관리 해볼까?"를 항상 생각하면서 개발하도록 하겠습니다!

2022-11-13 09:01 UTC, subroooo commented on src/modules/lesson/dtos/create-lesson.dto.ts
> +  hashtag: string[];
맞습니다 ApiProperty를 빼먹었네요..
LessonHashtagEntity를 만든 이후 해당 클래스에서 apiproperty를 작성해주고 picktype으로 받아오고 싶었지만  CreateLessonDto에서 받는 hashtag는 LessonHashtagEntity의 tag타입을 가지고 있는 게 아니라 string[] 타입을 가져야 
하기 때문에 picktype으로 따로 받지 않고 ApiProperty를 직접 만드는 방향으로 수정하였습니다!

2022-11-13 09:06 UTC, subroooo commented on src/modules/lesson/entities/lesson.entity.ts
> +import { Lesson as LessonModel } from '@prisma/client';
단순히 Post Module 보고 따라했습니다. 본질을 파악하지 못하고 단순히 따라만 했네요..

2022-11-13 10:38 UTC, subroooo commented on src/modules/lesson/entities/lesson.entity.ts
> +    example: 1,
넵!! enum을 적극적으로 활용하겠습니다!

2022-11-13 10:57 UTC, subroooo commented on src/modules/lesson/entities/lesson.entity.ts
> +    required: true,
찾아보니 기본 값이 false인 데코레이터는 ApiPropertyOptional이네요!! 좋은 정보 감사드립니다!

2022-11-13 11:12 UTC, subroooo commented on src/modules/lesson/entities/lesson.entity.ts
> +  levelId: number;
enum 적극 사용하는 것을 습관화 하도록 하겠습니다!

2022-11-13 11:29 UTC, subroooo commented on src/modules/lesson/entities/lesson.entity.ts
> +  @ApiProperty({
ApiProperty내에 최대, 최소 길이를 알려줄 수 있는 프로퍼티가 있을 것이라 생각하고 찾아 보았는데 maxLength와 minLength가 있었네요!! 이렇게 또 하나 알아갑니다!

2022-11-13 11:37 UTC, subroooo commented on src/modules/member/controllers/member.controller.ts
> +@Controller('api/members')
이번pr이 main에 merge가 될 때 클라이언트 팀에게 path 변경되었다고 알리겠습니다!!

2022-11-13 11:37 UTC, subroooo commented on src/types/type.ts
> +export type PrismaModel = 'user' | 'post' | 'member' | 'lesson';
감사합니다!

2022-11-13 11:42 UTC, subroooo commented on src/modules/member/entities/member.entity.ts
> +    description: 'member의 프로필 이미지',
좋습니다! faker js를 통해 example에 image url이라는 것을 알려주겠습니다!

2022-11-15 05:01 UTC, rrgks6221 requested changes

2022-11-15 05:01 UTC, rrgks6221 commented on src/modules/member/entities/member.entity.ts
> +    description: 'member의 프로필 이미지',
지금 fakerjs 가 devDependency 로 되어있어서 product 환경에서 충돌이 날 수도 있을거같아요.
그리고 문서에 들어가는 부분까지 다양한 예시를 줄 필요는 없을거같아서 꼭 faker 를 이용 안해도 되지 싶네요

2022-11-15 05:01 UTC, rrgks6221 commented on src/modules/member/controllers/member.controller.ts
> +@Controller('api/members')
main 에 머지될때 변경사항을 알리면 클라이언트 측에서 대응할 시간이 없을거같아서 백엔드 측에서 해당 path 에 대해 모두 동의한다면 미리 얘기하는게 좋을거같아요

2022-11-15 05:01 UTC, rrgks6221 commented on src/modules/lesson/entities/lesson.entity.ts
> +    type: 'number',
타입 삭제해주세요

2022-11-15 05:01 UTC, rrgks6221 commented on src/modules/lesson/entities/lesson.entity.ts
> +  tags?: LessonHashtagEntity[];
hit, memberId 의 ts 타입은 required 인데 apiProperty 상세는 optional 로 되어있어서 확인 한번 해주세요.
tags 의 apiProperty 가 들어가야하지 않나여??

2022-11-15 05:01 UTC, rrgks6221 commented on src/common/common.ts
> +export const createManyMapper = <T>(obj: {
클레스의 메서드로 만들어서 di 받아서 사용하는 방법으로 수정해주세요

2022-11-15 09:43 UTC, RokwonK commented on src/constants/enum.ts
> +}
석호님께서 말씀해 주신 방법이 깔끔한 것 같습니다! 에디터에서 주석을 볼 수 있다니!

2022-11-15 10:11 UTC, rrgks6221 commented on src/constants/enum.ts
> +}
그러면 앞으로 enum 또는 const 로 상수를 만들 때 주석을 다는 것으로 컨벤션을 가져가죠

2022-11-16 03:06 UTC, RokwonK approved these changes

2022-11-16 06:02 UTC, subroooo commented on src/modules/lesson/entities/lesson.entity.ts
> +  tags?: LessonHashtagEntity[];
맞네요 수정하겠습니다!

2022-11-16 10:54 UTC, rrgks6221 approved these changes
고생하셨습니다

2022-11-16 10:54 UTC, rrgks6221 commented on src/modules/lesson/services/lesson.service.ts
> +            data: this.prismaHelper.createManyMapper<{ tag: string }>({
prisma 메서드에 사용할 때 보통 entity 가 생성돼있을테니 typescript pick 을 사용할 수도 있겠네요

2022-11-21 03:37 UTC, rrgks6221 requested changes
코멘트 확인해주세요~~~

2022-11-21 03:37 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson.controller.ts
> +  @ApiNoContentResponse()
noContent 가 적절한 status 인지 확인해볼 필요가 있을거같아요 우선 저도 정확히 정확히 이해한건 아니라서 그대로 두고 나중에 검토해보도록 하죠

2022-11-21 03:37 UTC, rrgks6221 commented on src/modules/lesson/services/lesson.service.ts
> +    if (!updatedCount.count)
위에서 변수명이 updatedCount 로 지어버려서 count.count 라는 접근이 이상해보여요
그리고 if 문이 개행될 때 중괄호로 감싸주세요

2022-11-21 03:37 UTC, rrgks6221 commented on src/modules/lesson/services/lesson.service.ts
> +    const updatedCount = await this.prismaService.lesson.updateMany({
앞에서 해당 id 가 있는지 확인해서 업데이트된게 없으면 403 을 내려주는거같은데 이런건 빈번할테니 가드로 만들어서 처리하는게 좋을거같아요
제가 member 작업하면서 만들 예정이라 그때 수정하도록 하조

2022-11-21 04:12 UTC, subroooo commented on src/modules/lesson/services/lesson.service.ts
> +    if (!updatedCount.count)
변수명을 updatedLesson으로 변경하였고, if 문에 중괄호 추가하였습니다!

2022-11-21 04:24 UTC, subroooo commented on src/modules/lesson/services/lesson.service.ts
> +    const updatedCount = await this.prismaService.lesson.updateMany({
존재하는 과제인지 확인은 controller에서  @SetModelNameToParam,  IdRequestParamDto을 이용해서 검증을 하였고, 
유저는 UserLogin을 통해서 토큰에서 memberId를 꺼내긴했지만 존재하는 유저인지의 여부는 따로 파악하지 않았습니다.(추후에 가드로 만들어주셨을 때 추가하겠습니다!)

service의 updateLesson에서 updateMany에 where 조건을 두 개를 줌으로서 수정하려는 lessonId에 해당하는 memberId가 토큰에서 얻어온 memberId와 같은 경우에만 삭제가 되게끔 하려고 조건을 두개 준 것입니다.

2022-11-21 04:45 UTC, subroooo commented on src/modules/lesson/controllers/lesson.controller.ts
> +  @ApiNoContentResponse()
클라이언트의 응답은 성공했지만 응답으로 주어지는 요소는 없다는 의미로 204를 주었는데 
알아보니 put요청의 204는 자원 수정 요청의 결과가 기존의 자원 내용과 동일하여 변경된 내용이 없을 때 204로 응답하는 경우가 많더라구요!
수정 요청으로 자원의 내용이 변경된다면 201로 응답한다고 하니 우선 201로 변경하고
수정 성공에 대한 응답으로 수정된 자원들을 줄지에 대해서는 이야기 해봐야 할 것 같습니다!

2022-11-21 04:58 UTC, rrgks6221 approved these changes

2022-11-21 05:00 UTC, subroooo commented
![image](https://user-images.githubusercontent.com/86092785/202968652-98b3a407-2257-45df-8b95-a78548e6126a.png)

리소스 put,patch,delete 요청시 **본인이 생성한 리소스인지 확인하고 제한하는 가드 생성**하고 가드 사용하는 방향으로 수정

@RokwonK 
@rrgks6221

2022-11-21 09:51 UTC, RokwonK reviewed
고생많으셨습니다! Comment 한 번 확인해주세요!

2022-11-21 09:51 UTC, RokwonK commented on src/constants/enum.ts
> +  LessonHashTag = 'lessonHashtag',
HashTag로 할지 Hashtag로 할지 선택해서 통일시키는게 좋을 것 같습니다.

2022-11-21 09:51 UTC, RokwonK commented on src/modules/lesson/controllers/lesson.controller.ts
> +  }
udpateLesson과 updateLessonHashtag가 동기적으로 동작해야하는 이유가 있을까요?
없다변 Promise.all 로 묶어주는게 성능상 좋을 듯 합니다

2022-11-21 11:23 UTC, subroooo commented on src/constants/enum.ts
> +  LessonHashTag = 'lessonHashtag',
HashTag를 Hashtag로 전부 바꾼줄 알았는데 빼먹은 부분이 있었군요! 감사합니다

2022-11-21 11:55 UTC, subroooo commented on src/modules/lesson/controllers/lesson.controller.ts
> +  }
좋은 말씀 입니다!! 곧장 반영하겠습니다!

2022-11-22 00:51 UTC, merged