Feature/51 - major domain
the-pool/the-pool-api pull request #65
Opened 2022-12-04 11:27 UTC by rrgks6221

## Motivation
- 아래 4개 path 에 대한 api 및 테스트코드
  - /api/majors
  - /api/majors/:majorId
  - /api/majors/:majorId/mainSkills
  - /api/majors:majorId/mainSkills/:mainSkillId
- 기존에 존재하던 코드 리펙토링
- e2e test module set util function 생성
- README 에 Commit convention 테이블 추가
<img width="697" alt="image" src="https://user-images.githubusercontent.com/46591459/205487664-113f8d78-bfc2-4385-914c-2306f1ee6539.png">

<br>

## Key Changes
- major module

<br>

## To Reviewers
- 기존에 존재하던 코드 중 컨벤션 같은게 안맞던 것들도 몇개 수정해서 같이 껴있는데 major module 위주로 봐주시면 됩니다.
- README 에 Commit convention 테이블을 커밋할때마다 노션 들어가기 귀찮아서 README 에 우선 넣었는데 자유롭게 의견 주세요
- 지금 [prisma service mocking official guide](https://www.prisma.io/docs/guides/testing/unit-testing) 와 다르게 mocking 이 돼있는데 tsconfig.json 의  **"strictNullChecks": false,** 부분때문에 사용하지 못합니다. 저 옵션을 true 로 바꾸면 가이드대로 할 수 있는데 이미 구현된 코드의 상당 부분이 warning 이 돼서 이번 주말에 한번 얘기해보면 좋을거같아요.

2022-12-06 06:16 UTC, subroooo requested changes

2022-12-06 06:16 UTC, subroooo commented on src/modules/major/dto/major-relation-field-request-query.dto.ts
> +    enum: ['true', 'false'],
enum.ts에 만들어 놓으신 BooleanString 사용하지 않으신 이유가 있을까요?


```suggestion
    enum: [BooleanString.True, BooleanString.False] 
```

2022-12-06 06:16 UTC, subroooo commented on src/modules/major/controlles/major.controller.ts
> +    @Query() query: MajorRelationFieldRequestQueryDto,
query 파라미터를 활용해서 api에 추가 정보를 optional 하게 내려주는 방식 
멋지네요

2022-12-06 06:16 UTC, subroooo commented on src/modules/major/controlles/major.controller.ts
> +    return plainToInstance(MajorsDto, { majors });
클라이언트에게 전달하기 이전에 controller layer에서 한번 감싸주는 방식 너무 좋네요

2022-12-06 06:16 UTC, subroooo commented on src/modules/major/controlles/major.controller.spec.ts
> +      expect(mockMajorService.findMajors).toBeCalledWith(query);
test 하려는 메서드 내에서 호출되는 메서드의 인수가 정확하게 들어가는지
test해주는 toBeCalledWith 이렇게 하나 또 알아갑니다~

2022-12-06 06:16 UTC, subroooo commented on src/decorators/is-record.decorator.ts
> +export function IsRecord<M extends PrismaModel = PrismaModel>(
type으로 객체 형태인 target에 들어올 타입을 정의하고, 사용되는 곳에서 매개변수 그룹을 객체로 넘겨 받아 사용될 수 있도록 하는 방식 너무 좋네요

2022-12-06 06:16 UTC, subroooo commented on src/modules/lesson/services/lesson.service.spec.ts
> +          useValue: mockPrismaService,
MockPrismaService를 만들 때 일반 객체 형태로 만들긴 했지만 class의 Mock 역할을 하기에 의미론 적으로 클래스를 대신하는 것이라 생각해 파스칼 케이스로 네이밍을 했었는데, useValue 자리에 파스칼 케이스가 들어가니 의미가 맞지 않는다고 생각이 드네요! 
카멜케이스로 변경하신 선택이 좋은 선택인 것 같습니다!

2022-12-06 06:16 UTC, subroooo commented on src/modules/major/controlles/major.controller.spec.ts
> +        JSON.parse(faker.datatype.json()),
오.. 아직 faker에서 객체를 만들어 주는 기능을 제공하진 않나 보네요

2022-12-06 06:16 UTC, subroooo commented on src/types/type.ts
> +  | 'user';
```suggestion
export type PrismaModelName = Uncapitalize<Prisma.ModelName>;
```

찾아보니 Prisma에서 ModelName을 대문자로 제공하고 있더라구요!

저희가 만든 IsRecord 데코레이터에선 model name이 파스칼케이스가 아닌 
카멜케이스가 필요하기에 ts에서 제공하는 문자열 도우미 타입인 Uncapitalize을 이용할 수 있겠네요!

2022-12-06 06:16 UTC, subroooo commented on test/apis/majors.e2e.spec.ts
> +    stringMainSkillId = String(mainSkillId);
e2e test를 시작하기 이전에 먼저 major와 mainSkill을 뽑아놓고, 뽑힌 majorId, mainSkillId으로 test하는 방식 좋네요

2022-12-06 06:48 UTC, rrgks6221 commented on src/modules/major/dto/major-relation-field-request-query.dto.ts
> +    enum: ['true', 'false'],
저게 처음에 enum 사용했다가 머가 이상해서 바꾼걸로 기억하는데 한번 더 확인해보고 코멘트에 남기도록 할게여

2022-12-06 06:50 UTC, rrgks6221 commented on src/modules/major/controlles/major.controller.ts
> +    @Query() query: MajorRelationFieldRequestQueryDto,
이 컨셉 적용하면서 좋은 패턴인가에 대해 좀 고민됐는데 좋게 봐주셔서 좋네요

2022-12-06 06:51 UTC, rrgks6221 commented on src/modules/major/controlles/major.controller.spec.ts
> +      expect(mockMajorService.findMajors).toBeCalledWith(query);
이거 전에 알려줬는데...

2022-12-06 06:52 UTC, rrgks6221 commented on src/modules/major/controlles/major.controller.spec.ts
> +        JSON.parse(faker.datatype.json()),
네 제가 찾아봣을때는 object 자체를 주는 메서드는 없어서 json 메서드를 활용했습니다

2022-12-06 06:53 UTC, rrgks6221 commented on src/types/type.ts
> +  | 'user';
모델 생길때마다 수동으로 추가해줘야하나 찝찝했는데 좋네요. 남겨주신 방향으로 수정하도록 하겠습니다.

2022-12-06 07:33 UTC, subroooo commented on test/utils/setTestingApp.ts
> +        }),
AppModule에 이미 ConfigModule이 있는데 test 모듈을 생성하면서 재정의를 해준다면 AppModule에 있는 ConfgModule을 덮어 씌우는 건가요?

2022-12-06 07:39 UTC, subroooo commented on src/modules/major/controlles/major.controller.spec.ts
> +      expect(mockMajorService.findMajors).toBeCalledWith(query);
저는 말하는 감자입니다 흑흑

2022-12-06 07:53 UTC, subroooo commented on test/apis/majors.e2e.spec.ts
> +});
저희 파일명 컨벤션 단수 아니였나요

2022-12-06 09:05 UTC, rrgks6221 commented on test/utils/setTestingApp.ts
> +        }),
아주 좋은 질문이예요
답변부터 하자면 실수입니다.
처음에 setTestingApp을 만드려고 할 때  module 마다 독립적인 e2e 테스팅을 해야 모듈 크기가 작아져 테스팅하는 시간이 줄어들거라 생각해서 AppModule 을 imports 하는것이 아닌 테스팅 타겟 모듈만 빌드 시키려다가 실패하고 global module 인 config module 을 넣었다가 빼지 않았네요
config module import 를 빼거나 독립적인 모듈을 빌드하는 함수로 디벨롭하는 방향으로 수정하도록 할게요

2022-12-06 09:09 UTC, rrgks6221 commented on test/apis/majors.e2e.spec.ts
> +});
전에 논의가 됐었나요??
우선 복수로 한 이유는 네스트 기본 example 인 cats 모듈이 복수로 돼있었고 nest에서 기본적으로 들어가는 컨셉(네스트 cli 로 생성 가능한 애들)은 파일명과 클레스명을 동일하게 가져가서 한건데 얘기를 한번 해봐여겠네요

2022-12-06 10:00 UTC, RokwonK reviewed
작업하시느라 고생하셨습니다~!

2022-12-06 10:00 UTC, RokwonK commented on src/constants/constant.ts
> +};
지난번에 알려주셨던 as const 진행시키죠!

2022-12-06 10:00 UTC, RokwonK commented on src/modules/major/dto/majors.dto.ts
> +}
MajorDto와 구분이 힘들것 같은데 MajorListDto 형식으로 네이밍 바꾸는 건 어떨까요?

2022-12-06 10:00 UTC, RokwonK commented on src/constants/enum.ts
> +
같은 카테고리를 가지는 친구들을 나누어서 다룰 수 밖에 없다는게 마음 아픈 것 같습니다.
Type으로 사용하지 않는다면 MajorId, MajorText 모두 하나의 카테고리이니 부모카테고리로 만들어 버리는 건 어떤가요?
예를 들자면
```ts
const MajorInfo = {
  development: {
    id: 0,
    name: '개발'
  },

  design: {
    id: 1,
    name: '디자인'
  }
} as const;
```

2022-12-06 10:02 UTC, subroooo commented on test/apis/majors.e2e.spec.ts
> +});
The-Pool 노션에 회의 기록 > 백엔드 > 10.01 회의에 논의 했던 기록이 남아있습니다!
폴더, 파일명 컨벤션에 대해서 토요일날 한번 더 논의 해보는 것도 좋을 것 같네요!

2022-12-08 05:36 UTC, RokwonK reviewed
modules/major 밑에 controllers 디렉터리 오타있습니다.
controlles 로 되어 있네요
@rrgks6221

2022-12-08 14:21 UTC, RokwonK reviewed
마찬가지로 dto 디렉터리명도 dtos 로 수정해주세요!

2022-12-10 05:28 UTC, rrgks6221 commented
#67 작업이 선행돼야 해서 draft 상태로 변경하겠습니다.

2022-12-10 08:09 UTC, rrgks6221 commented on src/constants/enum.ts
> +
이 아이들은 타입으로 사용하고 있어용

2022-12-10 09:21 UTC, rrgks6221 commented
코멘트 반영 및 tsconfig 수정사항 대응 완료했습니다.

2022-12-11 05:31 UTC, subroooo approved these changes

2022-12-12 09:08 UTC, RokwonK approved these changes

2022-12-12 09:36 UTC, merged