Feature/70
the-pool/the-pool-api pull request #71
Opened 2022-12-31 06:36 UTC by subroooo

## Motivation
- 과제 해시태그 CRUD api

<br>

## Key Changes
- ApiSuccessResponse
- ApiFailureResponse
- PrismaHelper 클래스의 validateOwnerOrFail 메서드
- BearerAuth

<br>

## To Reviewers
-  swagger 상에 성공에 대한 응답으로 필드명을 커스텀하게 만들고 싶을 때 유용하게 사용될ApiSuccessResponse 
   데코레이터를 생성하였습니다.
- A라는 id를 가진 요소가 B라는 id를 가지는 요소의 자식 요소가 맞는지 확인해주는 validateOwnerOrFail 메서드를 
  만들었습니다.
- applyDecorators를 활용해 ApiBearerAuth, ApiFailureResponse의 Unauthorized, UseGuards를 합쳐주는 
   BearerAuth 데코레이터를 생성하였습니다.
- 이후 작업으로는 과제의 난이도 평가에 대한 CRUD api를 생성하는 작업을 하겠습니다.

2023-01-03 11:01 UTC, rrgks6221 reviewed
리뷰가 많아서 몇개가 숨겨졌는데 아래 사진 찾아서 펼쳐주세요
고생 많았습니다. 모든 코멘트를 다 수용할 필요없고 코멘트에 대한 피드백도 주세요 같이 성장하는 좋은 방법이라고 생각해요
<img width="835" alt="image" src="https://user-images.githubusercontent.com/46591459/210344761-76b55031-d000-46df-a92d-0412c70f2f83.png">

2023-01-03 11:01 UTC, rrgks6221 commented on prisma/seed.ts
> +    ],
skipDuplicated 빠진거같아요

2023-01-03 11:01 UTC, rrgks6221 commented on src/constants/constant.ts
> +export const DOMAIN_TO_MODEL_NAME = {
이거를 따로 빼서 선언해야하는 이유가 있나여??

2023-01-03 11:01 UTC, rrgks6221 commented on src/filters/not-found-error.filter.ts
> +@Catch(NotFoundError)
기존에 있는 HttpNotFoundExceptionFilter에 추가해도 되지 않나요??

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/hashtag/dtos/create-many-hashtag.dto.ts
> +  @IsString({ each: true })
저장하는 hashtag 의 최대길이가 없나요?? 있다면 dto 단에서 너무 긴 태그명이 올 때 쳐내는것도 고려해보면 좋을거같네요

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/hashtag/dtos/hashtag-param.dto.ts
> +  @Min(1)
Min 데코레이터에 number 타입 검사가 걸려있어서 다른 데코레이터를 추가하지 않은거같은데 float 형태가 오면 어떻게 되나요??

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/hashtag/dtos/update-hashtag.dto.ts
> +  @IsString()
여기도 태그명 길이 제한이 있다면 제한두는것도 고려해보면 졿을거같아요

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/hashtag/entities/hashtag.entity.ts
> +) {
혹시라도 프리즈마 모델이 없데이트 됐을 때 싱크가 안맞을 경우 빌드타임에서 잡을 수 있도록 entity 를 만들때는 impliment 를 사용하는게 좋을거같아요

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/hashtag/entities/hashtag.entity.ts
> +  modelId: number;
아 아이 무엇인지 설명 한번만 해줄 수 있나요??

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/core/database/prisma/prisma.helper.ts
> +    return this.prismaService[modelName].findFirstOrThrow({
findFirstOrThrow 는 프리즈마 내장 메서드인가요??
만약 내장 메서드라면 prismaService 에서 호출해도 괜찮을거같은데 한번 고민해주세요

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/core/database/prisma/prisma.helper.ts
> +  validateOwnerOrFail(
이 메서드 자체가 prismaService 와 동등한 레벨의 예외처리를 추가한거로 보이는데 prismaService에 메서드로 만들어도 되지 않을까싶어요

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +@Controller(':id/hashtags')
reponse body 에 hashtags 로 필드명을 주려하는거같은데 전처리 후처리에 동일한 로직이 들어갈 경우 떠올릴 수 있는게 있지 않나요?? 
숙제입니다
보니까 lesson controller도 똑같던데 동적으로 필드명을 줄 수 있으면 베스트이고요

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson.controller.ts
> +@Controller()
lesson hashtag controller 와 같은 코멘트

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/services/lesson-hashtag.service.ts
> +  async createHashtag(
주석 | 메서드명이랑 구현체랑 맞지 않는거같아요

2023-01-03 11:01 UTC, rrgks6221 commented on src/constants/constant.ts
> +export const SIMILAR_LESSON = {
예 좀비인가요?? 왜 다시 살아났지??

2023-01-03 11:01 UTC, rrgks6221 commented on src/decorators/api-success-response.decorator.ts
> +export const ApiSuccessResponse = (
이 데코레이터 상당히 잘 만들었는데 한가지 결점을 찾아버렸습니다...
```ts
{
  lessons: LessonEntity[],
  totalCount: number,
}
```
같이 원시값에 대한 타입은 생성할 수가 없네요... ㅜㅜ

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/hashtag/dtos/hashtag.dto.ts
> +export class HashtagDto {
이 아이 사용처가 없네요

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +  @ApiFailureResponse(HttpStatus.NOT_FOUND, "~ doesn't exist id in ~")
~ 로 표현하는거보다는 어떤 변수명으로 표현해주는게 좋겠어요
**'You do not have access to {modelName}'**
저기에 들어가는 변수명은 클라이언트 측에서 알아볼 수 있게끔 변수명을 짓는게 좋지 않을까 싶네요.

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +    return { hashtags: createdHashtags };
```suggestion
    );
    
    return { hashtags: createdHashtags };
```
진짜 사소한데 습관을 들이면 좋습니다!

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +  @ApiFailureResponse(HttpStatus.NOT_FOUND, "~ doesn't exist id in ~")
아래 더 보니 모든 path 에 대해 이 두개가 들어가는데  class 에 붙이거나 아니면 계속 복붙을 하고 수정을 하게되면 일일이 수정해야하니 하나의 클레스로 만들어서 사용하는것도 방법이겠어요.

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +  @ApiOperation({ summary: '과제 해시태그 단일 수정' })
swaager 에 대한 데코레이터는 사실 controller 에 노출되지 않아도 코드를 읽는데 문제가 없을거같아서 ApiOperation 만 주석느낌으로 놔두고 다른 swagger 관련 데코레이터는 다른 파일에서 관리하여 controller 의 메서드가 길어지는것도 방법일거같은데 다음에 한번 같이 얘기해봐요.
@RokwonK

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson.controller.spec.ts
> +    beforeEach(async () => {
```suggestion
    let mockLesson: Omit<LessonEntity, 'hashtag'>;
    
    beforeEach(() => {
```
구문간 \n 해주시고 필요없는 async 는 지워주세요

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson.controller.spec.ts
> +      mockLesson = plainToInstance(
단위테스트에서 controller 는 service 가 LessonEntity class 에 감싸진 애인지 plain object 인지에 따라 테스트가 달라져야 할 이유가 없어보이는데 한번 고려해주세요

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson.controller.ts
> +    const deletedLesson = await this.lessonService.deleteLesson(param.id);
```suggestion
    });
    
    const deletedLesson = await this.lessonService.deleteLesson(param.id);
```
허허

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson.controller.ts
> +    return lessons;
```suggestion
    return plainToInstance(ReadSimilarLessonDto, {
      lessons: readSimilarLessons,
    });
```
제 에디터 설정에서는 이렇게 고치는거 어떠냐고 물어보네요

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/services/lesson-hashtag.service.ts
> +      data: this.dataStructureHelper.createManyMapper<
data 에 들어가는 this.dataStructureHelper.createManyMapper 를 변수에 담는건 어떻게 생각하나요?? 지금 바로 인라인화 돼있어서 개인적으로 어떤 데이터셋이 반환될지 빠르게 감이 잡히진 않네요

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/services/lesson-hashtag.service.ts
> +  deleteManyHashtag(lessonId: number): PrismaPromise<{ count: number }> {
얘만 리턴타입이 PrismaPromise 인 이유가 있나요??

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/services/lesson-hashtag.service.ts
> +  deleteManyHashtag(lessonId: number): PrismaPromise<{ count: number }> {
명시적으로 count: number 로 타입을 지정해줘도 좋고 Prisma 에서 제공해주는 타입을 사용하고 싶다면 Prisma.BatchPayload 처럼도 사용할 수 있습니다. 프리즈마가 내부적으로 nameSpace 를 통한 타입을 가지고있어서 바로 못불러오고 Prisma 라는 nameSpace를 통해 접근하면 내부적으로 사용하는 타입에 접근이 가능해요.

2023-01-03 11:01 UTC, rrgks6221 commented on src/modules/lesson/services/lesson-hashtag.service.ts
> +  readHashtag(hashtagId: number): Promise<LessonHashtagEntity | null> {
many 메서드들처럼 readOneHashtag 이런 메서드명을 짓는거는 어떻게 생각하시나요??

2023-01-03 11:01 UTC, rrgks6221 commented on src/constants/constant.ts
> +export const DOMAIN_TO_MODEL_NAME = {
보라색이 사용처가 있는변수 짙은 회색이 사용처가 없는 변수인데 사용하지 않는 변수는 지워주세요

<img width="455" alt="image" src="https://user-images.githubusercontent.com/46591459/210344450-0bef5d98-c2d2-4af0-b909-81733900294c.png">

2023-01-04 00:47 UTC, subroooo commented on prisma/seed.ts
> +    ],
예리하시네요 감사합니다

2023-01-04 00:53 UTC, subroooo commented on src/constants/constant.ts
> +export const DOMAIN_TO_MODEL_NAME = {
위 pr만들면서 생성했던 IsHostGuard에 필요했던 변수인데 url에서 model을 뽑는 행위가 안티패턴인것 같아서 제거했는데
변수를 지우는 것을 깜빡했네요, 사용하지 않는 변수들 정리하도록 하겠습니다.

2023-01-04 01:31 UTC, subroooo commented on src/filters/not-found-error.filter.ts
> +@Catch(NotFoundError)
기존에 있던 HttpNotFoundExceptionFilter와 추가해주어도 되지만 NotFoundError는 에러를 만들어줄 때  message만 던져주고 있어서 filter에서 status와 err객체를 추가해주어야 하는데
`   
```
const status =   
       exception instanceof NotFoundException
        ? exception.getStatus()
        : HttpStatus.NOT_FOUND;
const err =
      exception instanceof NotFoundException
        ? (exception.getResponse() as ExceptionError)
        : exception;

```
   
기존 HttpNotFoundExceptionFilter의 status, err 변수가 위 처럼 변경되도 괜찮을까요?

2023-01-04 01:46 UTC, subroooo commented on src/modules/hashtag/dtos/create-many-hashtag.dto.ts
> +  @IsString({ each: true })
이번주 회의에서 유저가 해시태그를 동적으로 생성할 수 있는지 없는지에 대한 이야기를 해본 이후에 추가하도록 하겠습니다!

2023-01-04 02:17 UTC, subroooo commented on src/modules/hashtag/dtos/hashtag-param.dto.ts
> +  @Min(1)
float 형으로 들어오니 prisma에서 Argument id: Got invalid value 1.1 on prisma.findFirstLesson. Provided Float, expected IntFilter or Int에러가 발생하네요 
```suggestion
  @IsRecord({ model: ModelName.LessonHashtag, field: 'id' }, true)
  @Min(1)
  @IsInt()
  @Type(() => Number)
```
class-transformer에서 number변환 후 정수형이 맞는지 확인하는 IsInt를 추가해 주었고,  
IdRequestParamDto의 id에 대한 데코레이터에도 추가해 주겠습니다!

2023-01-04 02:26 UTC, subroooo commented on src/modules/hashtag/dtos/hashtag-param.dto.ts
> +  @Min(1)
현재 IdRequestParamDto에 데코레이터 순서가 
```
  @Min(1)
  @Type(() => Number)
  @IsRecord({}, true)
  id: number;
```
순으로 되어있는데 이렇게 되면 실행 순서가 Type > IsRecord > Min 순으로 실행되어 저희가 의도한데로 IsRecord에 들어갈 id에 대해서 방어가 불가능하게 되어
```
  @IsRecord({}, true)
  @Min(1)
  @IsInt()
  @Type(() => Number)
  id: number;
```
위 처럼 변경하여  Type > IsInt > Min > IsRecord 으로 실행되도록 변경하겠습니다

2023-01-04 02:31 UTC, subroooo commented on src/modules/hashtag/dtos/update-hashtag.dto.ts
> +  @IsString()
이 또한 이번주 회의 이후에 변경하도록 하겠습니다!

2023-01-04 04:32 UTC, subroooo commented on src/modules/hashtag/entities/hashtag.entity.ts
> +) {
과제뿐 아니라 다른 곳(유저의 해시태그, 질문의 해시태그)의 해시태그에도 포괄적으로 
HashtagEntity를 사용할 수 있도록 필드명을 포괄적인 modelId로 정했던 것인데 db에서 뽑혀오는 
컬럼명이 다르기 때문에 타입으로 사용하거나 엔티티 객체를 사용하는데 무리가 있겠네요 
prisma에서 만들어주는 LessonHashtag model을 impliment하고, 
클래스명을 HashtagEntity에서 LessonHashtagEntity로 변경하겠습니다.

2023-01-04 04:35 UTC, subroooo commented on src/modules/hashtag/entities/hashtag.entity.ts
> +  modelId: number;
위의 코멘트에 설명 남겨놓았습니다!

2023-01-04 05:02 UTC, subroooo commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +@Controller(':id/hashtags')
다른 팀원들 또한 사용할 수 있도록 interceptor 예쁘게 만들어 보겠습니다.

2023-01-04 05:22 UTC, subroooo commented on src/modules/core/database/prisma/prisma.helper.ts
> +    return this.prismaService[modelName].findFirstOrThrow({
프리즈마 내장 메서드라 PrismaService에서 호출하는게 더 좋은 것 같습니다!
이전에는 PrismaHelper 클래스에 메서드가 추가될 때마다 mock-helper.ts에 mockPrismaHelper에 
모킹할 메서드를 추가했어야 했는데 PrismaService에서 메서드를 만들어 놓으면 추가하지 않아도 되고 좋네요

2023-01-04 05:28 UTC, subroooo commented on src/modules/core/database/prisma/prisma.helper.ts
> +  validateOwnerOrFail(
prismaService에 옮겨 놓았습니다!

2023-01-04 08:09 UTC, RokwonK reviewed
저도 분발하겠습니다! 고생하셨어요😁
Comment 한 번 확인부탁드리겠습니다

2023-01-04 08:09 UTC, RokwonK commented on src/decorators/api-success-response.decorator.ts
> +export const ApiSuccessResponse = (
이거는 어쩔 수 없이 새로운 class를 만들어야겠군요..
totalCount 같은 Key를 갖는 제네릭 List를 만들죠!

2023-01-04 08:09 UTC, RokwonK commented on src/modules/core/database/prisma/prisma.helper.ts
> +   * A라는 id를 가진 자식요소가 B라는 부모 요소의 자식 요소가 맞는지 확인할 때 사용하려고 만든 메서드
현재 prismaHelper의 목적은 어떤건가요? 사실상 prismaServerice 그대로 사용하고 있다고 느껴서요

2023-01-04 08:09 UTC, RokwonK commented on src/modules/core/database/prisma/prisma.module.ts
>  export class PrismaModule {}
PrismaService와 PrismaHelper를 함께 사용하는 이유가 있을까요?
PrismaHelper를 Controller와 PrismaService의 중간 Layer로 두는 용도라면 PrismaHelper만 사용해도 문제없을 것 같다는 생각이 듭니다. 다른 목적으로 사용하시는 건가요?

2023-01-04 08:09 UTC, RokwonK commented on src/modules/hashtag/entities/hashtag.entity.ts
> +) {
@rrgks6221  implement시 빌드타임에서 잡을 수 있나요? 마찬가지로 컴파일타임에서 잡는 방법아닌가요?

2023-01-04 08:09 UTC, RokwonK commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +    });
이 두개는 Promis.all로 한꺼번에 처리해도 문제 없을 듯 싶습니다

2023-01-04 08:09 UTC, RokwonK commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +    });
마찬가지로 promise all로 처리해도 문제없을듯합니다

2023-01-05 02:03 UTC, subroooo commented on src/modules/hashtag/entities/hashtag.entity.ts
> +) {
@RokwonK implement가 ts개념이고, webpack 5.74.0 **compiled** with 1 error in 31535 ms 에러 메시지가 발생하는 걸 보면 컴파일 타임에서 잡는 것 같네요

2023-01-05 02:10 UTC, subroooo commented on src/modules/hashtag/dtos/hashtag.dto.ts
> +export class HashtagDto {
이 친구 @ApiOkResponse의 type에 넣으려고 만들어주었던 친구인데 @ApiSuccessResponse를 만들게 됨으로서 
사용하지 않게 되었습니다.(지우는 걸 깜빡했습니다 ㅎ)

2023-01-05 02:27 UTC, subroooo commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +  @ApiFailureResponse(HttpStatus.NOT_FOUND, "~ doesn't exist id in ~")
좋은 조언 감사드립니다.
constant.ts 파일에 HTTP에러 메시지를 메핑해주는 HTTP_ERROR_MESSAGE를 추가한 뒤 
```
export const HTTP_ERROR_MESSAGE = {
  FORBIDDEN: 'You do not have access to {modelName}',
  NOT_FOUND: "{modelId} doesn't exist id in {modelName}",
};
```

```suggestion
   @ApiFailureResponse(HttpStatus.FORBIDDEN, HTTP_ERROR_MESSAGE.FORBIDDEN)
  @ApiFailureResponse(HttpStatus.NOT_FOUND, HTTP_ERROR_MESSAGE.NOT_FOUND)
```
이런식으로 사용될 수 있도록 수정하겠습니다!

2023-01-05 02:35 UTC, subroooo commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +    return { hashtags: createdHashtags };
꼼꼼하게 하도록 하겠습니다!

2023-01-05 06:01 UTC, rrgks6221 commented on src/modules/hashtag/entities/hashtag.entity.ts
> +) {
저도 정확히는 모르는데
컴파일: 프로그래밍 언어를 기계어 또는 어셈블리어로 변환
빌드: 어플리케이션을 사용 가능한 프로그램으로 변환
혼용되어도 별로 상관은 없을거같네요

2023-01-05 06:57 UTC, rrgks6221 commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +    });
validation 부분을 promise all 로 처리하게 되면 예외처리에 추가적인 로직이 필요하게되고 나중에 해당 로직에서의 디버깅이 어려워져서 좀 신중할 필요는 있을거같네요

2023-01-05 07:42 UTC, RokwonK commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +    });
예외 처리에 문제가 생긴다고 한다면 Promise allSettled를 사용하는 방법으로 진행하면 좋을 것 같습니다!

2023-01-05 07:45 UTC, subroooo commented on src/modules/lesson/controllers/lesson.controller.spec.ts
> +    beforeEach(async () => {
넵 모든 파일에 필요없는 async 제거 및 구문 간 문단 나누기를 해주었습니다!

2023-01-05 08:02 UTC, subroooo commented on src/decorators/api-success-response.decorator.ts
> +export const ApiSuccessResponse = (
@rrgks6221 억장이 무너지네요....

2023-01-05 08:15 UTC, subroooo commented on src/modules/lesson/services/lesson-hashtag.service.ts
> +  readHashtag(hashtagId: number): Promise<LessonHashtagEntity | null> {
단일 생성에 대한 메서드는 One을, 다중 생성에 대한 메서드는 Many를 붙이는 것으로 수정하겠습니다!

2023-01-05 08:20 UTC, subroooo commented on src/modules/lesson/services/lesson-hashtag.service.ts
> +  deleteManyHashtag(lessonId: number): PrismaPromise<{ count: number }> {
Promise<{ count: number }>로 수정하였는데 Prisma.BatchPayload를 사용해 Promise<Prisma.BatchPayload>로 하는 것도 괜찮아 보이네요 

BatchPayload로 바로 접근 불가능한 이유가 내부적으로 nameSpace를 통한 타입을 가지고 있어서 였군요! 또 하나 알아갑니다

2023-01-05 08:34 UTC, subroooo commented on src/modules/lesson/controllers/lesson.controller.spec.ts
> +      mockLesson = plainToInstance(
plainToInstance에서 new 키워드를 통해 생성하는 것으로 변경하였습니다.

2023-01-05 08:37 UTC, subroooo commented on src/modules/lesson/controllers/lesson.controller.ts
> +    return lessons;
가만 생각해 보니 의미 없는 변수 할당이네요

2023-01-05 08:48 UTC, subroooo commented on src/modules/lesson/services/lesson-hashtag.service.ts
> +      data: this.dataStructureHelper.createManyMapper<
좋은 리뷰 감사합니다! 지금 생각해보니 남들이 보았을 때 가독성이 엉망인 코드인 것 같아 부끄럽네요
인라인 되어있는 메서드를 변수로 추출해서 할당하도록 하겠습니다

2023-01-05 08:53 UTC, subroooo commented on src/modules/core/database/prisma/prisma.helper.ts
> +   * A라는 id를 가진 자식요소가 B라는 부모 요소의 자식 요소가 맞는지 확인할 때 사용하려고 만든 메서드
PrismaService에서는 prisma관련 로그 설정 및 기초 세팅을 하는 기능만 하는 클래스라고 판단해
prisma 빌트인 메서드를 응용하는 메서드를 작성하는 클래스인 PrismaHelper를 만들었습니다.

두 분의 의견을 듣고, 위 두 메서드가 PrismaService에 있어도 문제 없을 것 같아 PrismaHelper클래스를 삭제하고,
PrismaService 클래스에 두 메서드를 옮겨 놓았습니다!

2023-01-05 08:54 UTC, subroooo commented on src/modules/core/database/prisma/prisma.module.ts
>  export class PrismaModule {}
바로 위 코멘트에 답글 담겨 놓았습니다!

2023-01-05 11:54 UTC, subroooo commented on src/modules/lesson/controllers/lesson-hashtag.controller.ts
> +    });
await Promise.all([
      this.prismaService.validateOwnerOrFail(ModelName.Lesson, {
        id: param.id,
        memberId,
      }),
      this.prismaService.validateOwnerOrFail(ModelName.LessonHashtag, {
        id: param.hashtagId,
        lessonId: param.id,
      }),
    ]);

특정 테이블의 row를 추가, 수정, 삭제하는 메서드들이 아닌 get 요청에 대한 메서드들이기 때문에 Promise.all로 처리해도 무방할 것 같습니다.

2023-01-05 14:24 UTC, RokwonK approved these changes

2023-01-06 04:54 UTC, rrgks6221 requested changes

2023-01-06 04:54 UTC, rrgks6221 commented on src/modules/core/database/prisma/prisma.service.ts
> +  findOneOrFail(modelName: PrismaModelName, where: any): Promise<PrismaModel> {
얘랑 아래 메서드의 where 타입을 프리즈마에서 제공해주는데 찾아서 추가해주세요
타입을 any 가 아닌 제공해주는 타입을 써야하는 이유는 개발편의성, 실제 사용처에 500에러 최소화 등입니다

2023-01-06 04:54 UTC, rrgks6221 commented on src/modules/hashtag/dtos/hashtag-param.dto.ts
> +  @Min(1)
데코레이터 순서에 관계없이 validator 보다 transform 이 먼저 실행돼서 Type 데코레이터 순서는 크게 의미 없지먼 라이브러리에 관계없이 데코레이터 실행 순서를 알기 위해 컨벤션으로 아랭 두는것도 좋겠네요

2023-01-06 04:54 UTC, rrgks6221 commented on src/modules/hashtag/entities/lesson-hashtag.entity.ts
> +  @ApiProperty({
어디는 required, type ㅍoption 을 쓰고 어디는 안쓰고있는데 같이 얘기해서 통일해보면 좋겠네요
@RokwonK

2023-01-06 05:02 UTC, subroooo commented on src/modules/core/database/prisma/prisma.service.ts
> +  findOneOrFail(modelName: PrismaModelName, where: any): Promise<PrismaModel> {
where 조건이 각각의 모델마다 UserWhereInput, PostWhereInput, LessonBookmarkWhereInput 이런식으로 분리되어 
만들어져 있어서 any로 준 것 인데 prisma에서 where 조건을 모아둔 타입이 있는지 찾아봐야겠네요!

2023-01-06 06:18 UTC, subroooo commented on src/modules/core/database/prisma/prisma.service.ts
> +  findOneOrFail(modelName: PrismaModelName, where: any): Promise<PrismaModel> {
찾아보니 따로 Prisma에서 risma.ModelName 처럼 따로 모델의 whereInput 조건에 들어갈 수 있는 타입을 모아 놓은 타입을 제공하지 않는 것 같더라구요 
우선 type.ts에 
```
export type PrismaWhereInput =
  | Prisma.PostWhereInput
  | Prisma.UserWhereInput
  | Prisma.MajorWhereInput
  | Prisma.LessonWhereInput
  | Prisma.MainSkillWhereInput
  | Prisma.LessonLikeWhereInput
  | Prisma.PostScalarWhereInput
  | Prisma.LessonLevelWhereInput
  | Prisma.MemberSkillWhereInput
  | Prisma.LessonScalarWhereInput
  | Prisma.MemberFollowWhereInput
  | Prisma.MemberReportWhereInput
  | Prisma.MemberScalarWhereInput;
```
위 처럼 정의해 놓았는데 위 처럼 하면 model늘어날 때마다 일일이 추가해 주어야 해서 개선할 필요가 있어 보입니다...

2023-01-06 07:51 UTC, rrgks6221 approved these changes

2023-01-07 05:32 UTC, merged