Feature/55
the-pool/the-pool-api pull request #75
Opened 2023-01-14 10:08 UTC by rrgks6221

# 죄송합니다......

## Motivation

- example 코드인 User, Post 관련 코드 삭제
- elastic module, search module 추가 (현재 사용 X 추후에 사용)
- seed file 분리
- SetResponseInterceptor 추가
  - 객체로 한번 래핑하는 인터셉터
  - Before
  ```json
  {
    "id": 1
  }
  ```
  - After
  ```json
  {
    "example": {
      "id": 1
    }
  }
  ```
- UseDevelopmentInterceptor 추가
  - production 환경에서 사용되면 안되는 api 를 404 로 바꾸는 인터셉터
- IncreaseMemberReportInterceptor 추가
  - member 의 count 관련한 액션을 했을 때 count 를 증가 또는 감소시키는 인터셉터 사용처는 To Reviewers
- member (/api/members)
  - 개발환경에서만 사용 가능한 accessToken 발급 api 생성
  - member 단일조회 api
  - 회원가입 | 로그인 api
  - patch update api
  - 기존의 소셜로그인 api deprecated 표시
  - 기존의 patch update deprecated 표시
- member friendship (팔로우) (/api/member-friendships)
  - member 의 follower 리스트 조회 api
  - member 의 following 리스트 조회 api
- member interest (관심사) (/api/member-interests)
  - member 관심사 리스트 조회 (특정 member 의 관심사는 queryString 으로)
- member report (member 통계 관련) (/api/member-reports)
  - member report 리스트 조회
  - member report 단일 조회
- member skill (/api/member-skills)
  - member skill 리스트 조회 (특정 member 의 스킬은 queryString 으로)

<br>

<br>

## To Reviewers

- prisma seed 파일 분리했습니다.
  - 이제 새로운 seed 를 만들 때 /prisma/functions 디렉토리에 {model}.seed.ts 파일로 만들어주시고 import 해서  사용해주세요.
- 지금 /api/members 도메인 제외하고는 GET 관련한 api 만 만들었는데 다른 메서드 api 는 추후에 추가하도록 하겠습니다.
- api, interceptor 만들어놓은거를 major module 에는 해당 pr 에서 적용하지 않았고 다른 pr 에서 처리하겠습니다.
- 단위테스트는 만들었는데 e2e 테스트는 추가 못했습니다. 추후에 추가 하겠습니다.
- IncreaseMemberReport 데코레이터를 아래 동작이 들어가는 api 에 추가해주세요
  - lesson 생성, 삭제시
  - feedback 생성, 삭제시
  - comment 생성, 삭제시
- e2e test script config 변경
  - e2e test 작성 시 /test/apis/{module}.e2e-spec.ts 형식으로 생성해줘여 npm run test:e2e 실행시 테스트코드가 실행됩니다.

2023-01-15 09:09 UTC, subroooo requested changes
고생하셨습니다~ member 모듈에 대한 comment는 내일 남기도록 할게요!

2023-01-15 09:09 UTC, subroooo commented on prisma/seed.ts
> +  await majorSkillSeed(prisma);
아주 만족스럽네요

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-report/controllers/member-report.controller.ts
> +  @Get(':memberId')
MemberReport 테이블의 고유 ID가 아니라 memberId를 받으셨는데
Member와 MemberReport의  관계가 OneToOne 이기에 위 방식처럼 하신건가요?

restful 한 관점에서 생각해 보았을 때 Member와 MemberReport 테이블이 분리되어 있기 때문에 해당 테이블의 고유 id를 받는 것이 더 좋다고 생각이 드는데
@rrgks6221 @RokwonK  다른 분들은 OneToOne 관계에서 자식 도메인의 id에 대한 path 어떻게 생각하시나요?

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-report/dtos/find-member-report-list-query.dto.ts
> +) {}
추후에 랭킹 조회, 피드백 갯수 순으로 조회 이런 기능이 추가 된다면 위 dto가 재미있어 지겠네요!

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-report/services/member-report.service.ts
> +    const where = this.queryHelper.buildWherePropForFind(filter);
buildWherePropForFind 구현부 likeSearchFields가 가상 컬럼 내부의 컬럼인 경우 
대응되지 못하는 것 같은데 개선 해주실 @RokwonK @rrgks6221 구합니다

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-report/services/member-report.service.ts
> +  }
prisma에서 트랜잭션을 처리하는 방식이 여러가지가 있는 걸로 알고 있는데 
개인적으로 위 방식처럼 $transaction 상단에서 promise한 prisma 빌트인 메서드들을 변수에 담고 $transaction에 넣어주는 방식이 가장 좋다고 생각이 드네요

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-report/services/member-report.service.ts
> +    const order = this.queryHelper.buildOrderByPropForFind([orderBy], [sortBy]);
@rrgks6221 @RokwonK buildOrderByPropForFind 이거 구현부 orderBy, sortBy의 순서에 대한 제어가 안전하게 이루어지지 못하다고 생각이 드는데 지금 보다 더 좋은 방법을 논의해 보아야 할 것 같아요.

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-report/services/member-report.service.ts
> +      where,
return 타입이 없네요??

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-report/controllers/member-report.controller.ts
> +  findOne(@Param() params: FindMemberReportRequestParamDto) {
return 타입이 없어요

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-report/services/member-report.service.spec.ts
> +        take: expect.anything(),
null 이나 undefined를 제외한 모든 값을 허용하는 expect.anything() 
또 하나 배워가네요

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-report/services/member-report.service.spec.ts
> +    let totalCount: number;
```suggestion
    let memberReports: Promise<MemberReportEntity[]>;
    let totalCount: Promise<number>;
```

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-report/services/member-report.service.spec.ts
> +      totalCount = faker.datatype.number();
```suggestion
      memberReports = new Promise(() => [new MemberReportEntity()]);
      totalCount = new Promise(() => faker.datatype.number());
```

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-report/services/member-report.service.spec.ts
> +        Promise.resolve(totalCount),
```suggestion
        memberReports,
        totalCount
```

memberReports와 totalCount의 선언과 할당을 Promise 타입으로 주면 toBeCalledWith 내부에서 Promise.resolve를 할 필요가 없을 것 같습니다!

추가로 mockResolvedValue가 ResolvedValue를 받기 때문에 더 적합하다고 생각합니다!

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-report/services/member-report.service.spec.ts
> +    let where: Prisma.MemberReportWhereInput;
그간 Prisma namespace 사용하는 타입에 대해서는 any를 적어주었는데
반성하게되네요... 저도 test 코드 짤 때 타입에 좀 더 신경쓰도록 하겠습니다!

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-friendship/services/member-friendship.service.ts
> +  async findAll(
이 아이 물건이네요?

2023-01-15 09:09 UTC, subroooo commented on src/modules/member-friendship/services/member-friendship.service.spec.ts
> +
요만큼 test case 중복이 발생하는 것 같은데 beforeEach에 들어가는게 더 낫지 않나요?

2023-01-16 07:11 UTC, subroooo requested changes

2023-01-16 07:11 UTC, subroooo commented on src/modules/member/services/member.service.ts
> +    }) as Promise<MemberEntity>;
```suggestion
   findOne(where: Prisma.MemberWhereInput): Promise<MemberEntity | null> {
    return this.prismaService.member.findFirst({
      where,
    }) 
```

범용성 있는 사용을 위해 단일 조회를 findUnique가 아닌 findFirst로 선택 하신 것  좋은 선택이었다고 생각합니다.

그러나 findFirst와 같은 경우 where 조건에 해당하는 유저가 없다면 null을 return 해주는 것으로 알고 있는데, as 로 MemberEntity 타입을 단정 짓는 것이 아닌 return 타입에 유니온으로 null을 명시해주는 건 어떤가요?

2023-01-16 07:11 UTC, subroooo commented on src/modules/member/controllers/member.controller.ts
> +    @SetModelNameToParam('member')
```suggestion
    @SetModelNameToParam(ModelName.Member)
```

저희 enum.ts에 ModelName을 string 형태로 매핑해 놓은 enum이 있는데 해당 enum에 Member 추가해서 불러다가 사용하는 방식이 더 좋은 것 같습니다!

2023-01-16 07:11 UTC, subroooo commented on src/modules/member/controllers/member.controller.ts
> +  getAccessTokenForDevelop(@Param() params: { id: string }): string {
이 아이 제가 만들었어야 했는데 떠넘겼네요 죄송함다..

2023-01-16 07:11 UTC, subroooo commented on src/interceptors/use-development.interceptor.ts
> +export class UseDevelopmentInterceptor implements NestInterceptor {
이 친구 개발 환경에서만 사용하는 api에 대해서 제한 사항을 주려고 만드신 친구인 것 같은데 가드가 아닌 인터셉터로 구현하신 이유가 있으신가요?

2023-01-16 07:11 UTC, subroooo commented on src/modules/member/controllers/member.controller.ts
> +    @UserLogin() member: MemberEntity,
OptionalJwtAuth 가드와 UserLogin 파라미터 데코레이터를 함께 사용하는 경우 
토큰이 존재하지 않는 경우에 { id : null}이 들어올 수 있는데 명시적으로 member타입에{ id : null }을 추가해 주는 건 어떤가요?

2023-01-16 07:11 UTC, subroooo commented on src/modules/member/services/member-validation.service.ts
> +            nickname: updateInfo.nickname,
NOT 활용 야무지네요

2023-01-16 07:11 UTC, subroooo commented on src/modules/member/services/member-validation.service.ts
> +  async canUpdateFromPatchOrFail(
분기처리 야무집니다

2023-01-16 07:11 UTC, subroooo commented on src/modules/member/dtos/patch-update-member-request-body.dto.ts
> +  @MaxLength(30)
MaxLength가 IsString역할도 해주는군요! 또 하나 알아가네요

2023-01-16 10:32 UTC, rrgks6221 commented on src/modules/member-report/controllers/member-report.controller.ts
> +  @Get(':memberId')
이게 one to one 관계인데 사실상 one to many 로 row 가 들어가서 정합성이 깨질수도 있는데 차라리 memberReport 테이블에 id 를 지우고 memberId 를 Pk 로 가지게 하여 one to one 관계를 확실히 하는건 어떻게 생각하시나요???

2023-01-16 10:32 UTC, rrgks6221 commented on src/modules/member-report/dtos/find-member-report-list-query.dto.ts
> +) {}
이런 악질

2023-01-16 10:35 UTC, rrgks6221 commented on src/modules/member-report/services/member-report.service.ts
> +    const where = this.queryHelper.buildWherePropForFind(filter);
```ts
// search 조건 build
    const whereDepth1 = this.queryHelper.buildWherePropForFind(filter);
    const whereDepth2 = this.queryHelper.buildWherePropForFind(filter);
    // order 조건 build
    const order = this.queryHelper.buildOrderByPropForFind([orderBy], [sortBy]);

    // 프로미스한 findMany 만 만들어놓는다.
    const memberReportsQuery: PrismaPromise<
      (MemberReportEntity & { member: MemberEntity })[]
    > = this.prismaService.memberReport.findMany({
      where: {
        ...whereDepth1,
        member: {
          ...whereDepth2,
        },
      },
      orderBy: order,
      skip: page * pageSize,
      take: pageSize,
      include: {
        member: true,
      },
    });
```
우선은 요런식으로는 사용 가능하긴 해요

2023-01-16 10:35 UTC, rrgks6221 commented on src/modules/member-report/services/member-report.service.ts
> +  }
캄사합니다~

2023-01-16 11:09 UTC, rrgks6221 commented on src/modules/member/services/member.service.ts
> +    }) as Promise<MemberEntity>;
타입 단언을 한 이유는 pipe 레이어에서 한번 검증을 하기때문인데 service 에서는 해당 정보에 상관없이 동작해야하니 예외처리를 하는게 맞을까요???

2023-01-16 11:16 UTC, rrgks6221 commented on src/interceptors/use-development.interceptor.ts
> +export class UseDevelopmentInterceptor implements NestInterceptor {
가드는 인증 또는 인가에만 사용하고 인터셉터는 전처리 또는 후처리에 대한 처리를 해야한다고 생각해서 인터셉터로 구현했는데 사실상 미들웨어가 가장 적당할거같네요 미들웨어로 수정하도록할게요

2023-01-16 11:39 UTC, rrgks6221 commented on src/modules/member-report/services/member-report.service.ts
> +    const order = this.queryHelper.buildOrderByPropForFind([orderBy], [sortBy]);
이 부분 수정 했어요~~

2023-01-16 11:40 UTC, rrgks6221 commented
@subroooo https://github.com/the-pool/the-pool-api/pull/75#discussion_r1070514334
이 코멘트 제외하고 코멘트 반영했습니다~~~

2023-01-16 11:55 UTC, rrgks6221 commented on src/modules/member/services/member.service.ts
> +    }) as Promise<MemberEntity>;
> 타입 단언을 한 이유는 pipe 레이어에서 한번 검증을 하기때문인데 service 에서는 해당 정보에 상관없이 동작해야하니 예외처리를 하는게 맞을까요???

요것도 의견주세요

2023-01-17 11:29 UTC, subroooo commented on src/interceptors/use-development.interceptor.ts
> +export class UseDevelopmentInterceptor implements NestInterceptor {
좋습니다!

2023-01-17 11:46 UTC, subroooo commented on src/modules/member/services/member.service.ts
> +    }) as Promise<MemberEntity>;
범용성있게 findOne를 사용하는 경우 where 조건에 여러 다른 케이스들이 들어올 것으로 예상되는데,
그럴 때마다 앞단에서 pipe로 리소스 존재 유무를 확인하고 사용하는데 불편함이 있지 않을까요?

위의 적용하신 예시는 id를 통한 리소스 검증일 때여서 IdRequestParamDto와 IsRecord를 사용해 리소스 유무를 편하게 검증했지만 where 조건에 id가 아닌 값이 들어오는 경우에는 사용하기 어려울 것 같다는 생각이 듭니다.

2023-01-17 12:02 UTC, subroooo commented on src/modules/member-report/controllers/member-report.controller.ts
> +  @Get(':memberId')
저는 괜찮다고 생각합니다.

2023-01-17 12:19 UTC, rrgks6221 commented on src/modules/member/services/member.service.ts
> +    }) as Promise<MemberEntity>;
오 그러네요 상당히 인정하는 부분입니다.

2023-01-17 12:24 UTC, RokwonK reviewed
코드뿐만 아니라 테스트 코드도 작성하시느라 고생많으셨습니다!

2023-01-17 12:24 UTC, RokwonK commented on prisma/seed.ts
> +  await majorSkillSeed(prisma);
농사왕 갓석호님 최고

2023-01-17 12:24 UTC, RokwonK commented on src/decorators/increase-member-report.decorator.ts
> +export const IncreaseMemberReport = (
변수명이 조금 모호하다고 하면 석호님께 혼날까요? 보통 Report는 신고할때 사용하다보니 다른 네이밍은 어떠신지요? IncreaseMemberSubAction 이라던지 등등

2023-01-17 12:24 UTC, RokwonK commented on src/middlewares/use-development.middleware.ts
> +}
오 너무 좋네요!

2023-01-17 12:24 UTC, RokwonK commented on src/modules/core/auth/helpers/auth.helper.ts
> +
저희 결국 체킹하는 로직의 접두사는 validate로 하기로 결정났나요?

2023-01-17 12:24 UTC, RokwonK commented on src/modules/member-friendship/services/member-friendship.service.ts
> +
주석 너무 감사합니다!

2023-01-17 12:24 UTC, RokwonK commented on src/modules/member-report/controllers/member-report.controller.ts
> +  @Get(':memberId')
일단 다른 얘기로 report라는 단어가 헷갈렸습니다. 보통 Report는 유저들 신고할때 많이 사용하는데 여기서 report는 멤버 활동내역을 확인하는 것 같은데 맞을까요? 아마 유저신고 기능이 들어가게 될텐데 해당 기능의 네이밍과도 다소 헷갈릴 우려가 있을 것 같다고 생각됩니다.

저는 석호님이 말씀하신것처럼 memberId를 PK로 가지는 one To one 관계가 좋을 것 같습니다!

2023-01-17 12:24 UTC, RokwonK commented on src/modules/member-report/services/member-report.service.ts
> +  }
그때 얘기하다 말았었다가 생각났습니다. transaction 처리시 커스텀 가능 한 transaction 처리를 위해 석호님께서 prisma 4.7로 업그레이드 하자고 말씀하셨습니다. 
아래 링크의 interaction transaction 파트에서 해당 부분을 확인하실 수 있습니다!
[interaction transaction](https://www.prisma.io/docs/concepts/components/prisma-client/transactions)

2023-01-17 12:24 UTC, RokwonK commented on src/modules/member/controllers/member.swagger.ts
> +};
센스 최고십니다!

2023-01-17 12:29 UTC, rrgks6221 commented on src/decorators/increase-member-report.decorator.ts
> +export const IncreaseMemberReport = (
이사람 영어 잘한다...
코멘트는 언제나 환영이죠. 저 변수명을 잘 못짓는편이라... 록원님 코멘트 보니 report 가 조금 애매하긴 하네요 model 명부터 memberStatistics 같이 바꾸고 관련된 애들도 변경하도록 할게요 지금 생각나는건 memberStatistics 인데 더 좋은 model 명 있으면 말씀해주세요

2023-01-17 12:30 UTC, rrgks6221 commented on src/modules/core/auth/helpers/auth.helper.ts
> +
변수명의 접두사까지 컨벤션으로 가져가기에는 개발 전 리소스가 너무 많이 들어갈거같습니다. 우선 수형이랑 저랑 validate 접두사로 시작된건 우연입니다...

2023-01-17 12:34 UTC, rrgks6221 commented on src/modules/member/controllers/member.swagger.ts
> +};
OneToOne 관계 관련한거는 수형이도 조금 고민해보고 답 준다고 해서 의견 취합해서 결정되면 한번 더 말씀 드릴게요.
아직 prisma 버전 업을 하지 안았는데 우선 제가 작업한 부분에서는 트렌젝션 내 분기처리가 필요하지 않아서 nteraction transaction 은 사용하지 않아도 될거같습니다.
prisma 버전은 업 시켜서 다시 리뷰 요청드릴게요

2023-01-18 11:05 UTC, rrgks6221 commented
@RokwonK @subroooo 
수정사항 반영했습니다.
pr 자체가 크다보니 커밋단위로 볼 수 있게 기능별로 커밋해서 커밋별로 봐도 될듯해요

2023-01-18 12:46 UTC, subroooo commented on src/modules/core/auth/helpers/auth.helper.ts
> +
전부터 validate 해주는 메서드는 앞에 prefix로 validate를 붙여주었어서 저는 이게 익숙하네요 ㅎㅎ

2023-01-18 12:49 UTC, subroooo approved these changes

2023-01-19 08:25 UTC, RokwonK approved these changes
Good!

2023-01-19 10:04 UTC, merged

2023-02-04 05:55 UTC, PD-hyelin commented on src/decorators/increase-member-report.decorator.ts
> +export const IncreaseMemberReport = (
이사람 영어 잘한다