Feature/78
the-pool/the-pool-api pull request #82
Opened 2023-01-21 08:30 UTC by rrgks6221

## Motivation
- member 가 major 를 선택하는 api
  - POST /api/member/:memberId/majors/:majorId
- OwnMemberSetMetadataGuard 생성
- AllowMemberStatusesSetMetadataGuard 생성
- MemberMajorSetMetadataGuard 생성

<br>

## Key Changes
-

<br>

## To Reviewers
-

2023-01-24 06:42 UTC, subroooo requested changes
고생하셨습니다! 이번주 작업량 대단하시네요...ㄷㄷ

2023-01-24 06:42 UTC, subroooo commented on src/guards/member-major.guard.ts
> + */
위 가드를 applyDecorator를 통해 확장해 놓은 데코레이터(MemberMajorSetMetadataGuard)가 있다는 것도 주석으로 추가해 주시면 좋을 것 같습니다!

2023-01-24 06:42 UTC, subroooo commented on src/guards/own-member.guard.ts
> +export class OwnMemberGuard implements CanActivate {
이 친구 야무지네요

2023-01-24 06:42 UTC, subroooo commented on src/guards/member-major.guard.ts
> +    return true;
1. major을 이미 선택한 유저들을 막기 위한 guard
2. major에 따른 접근 제한을 두고 싶을 때를 위한 guard (SetMetadata필요)
major를 선택하지 않은 유저들을 막기 위한 가드는 SetMetadata로 모든  major를 넣으면 되는군요! 

major에 따른 제한을 둘 것인가 의논해 보아야겠지만 확장성 있게 잘 만드셨네요

2023-01-24 06:42 UTC, subroooo commented on test/mock/mock-libs.ts
> +export const mockReflector = {
오호.. 라이브러리 모킹할 때 mock-libs에 정의해 놓으면 되는 군요.. 저번 pr때 왜  못봤지..??

2023-01-24 06:42 UTC, subroooo commented on src/guards/own-member.guard.spec.ts
> +    });
test 코드 짤 때 비동기가 아니더라도 throw error 에 대해서는 async await 걸어주어야 하는 줄 알고 있었는데 그동안 expect().toThrowError를 잘못 사용하고 있었네요...

2023-01-24 06:42 UTC, subroooo commented on src/modules/major/entities/major.entity.v2.ts
> +export class MajorEntityV2 extends IdResponseType implements Major {
워낙 기존 MajorEntity가 널리 사용되고 있다보니 MajorEntity 이전하시는 작업하시면서 고생 좀 하시겠네유... 
저도 LessonEntity 가상 컬럼 빼면서 애를 좀 먹었습니다 ㅠㅠ

2023-01-24 06:42 UTC, subroooo commented on test/mock/mock.type.ts
> +};
test 코드에도 타입을 빡빡하게 도입하는 그는 도덕책...

2023-01-24 06:42 UTC, subroooo commented on src/guards/member-major.guard.spec.ts
> +        }).toThrowError('Development, Design major 유저만 접근 가능합니다.');
```suggestion
 describe('특정 major를 선택한 member만 허용 ', () => {
      beforeEach(() => {
        majorId = faker.helpers.arrayElement([
          MajorId.Development,
          MajorId.Design,
        ]);
        allowMemberMajors = [majorId];

        mockReflector.get.mockReturnValue(allowMemberMajors);
      });

      it('성공 케이스', () => {
        member.majorId = majorId;
        mockRequest.user = member;

        expect(memberMajorGuard.canActivate(mockContext)).toBeTruthy();
      });

      it('실패 케이스', () => {
        member.majorId = null;
        mockRequest.user = member;

        expect(() => {
          memberMajorGuard.canActivate(mockContext);
        }).toThrowError(`${MajorId[majorId]} major 유저만 접근 가능합니다.`);
      });
    });
```
  faker.helpers.arrayElement([])를 사용하는 방식은 어떻게 생각하시나요? 
 "faker.heplers.arrayElements"를 이용하면 배열에서 선택하고 싶은 개수도 고를 수있는 것 같네요 it.each와 응용하면 좋을 것 같아요

2023-01-25 12:54 UTC, RokwonK reviewed
늦은 리뷰해서 죄송합니다ㅜ 네이밍 바꾸는 것도 그렇고 노가도 작업도 많고 고생 많으셨습니다!
코멘트 한 번만 확인 부탁드릴게요~

2023-01-25 12:54 UTC, RokwonK commented on src/guards/member-major.guard.ts
> +    }
array 프로토타입에도 include가 존재하는걸로 알고있는데 `join` 메서드 필요없을 것 같습니다!

2023-01-25 12:54 UTC, RokwonK commented on src/guards/member-status.guard.ts
> +    }
마찬가지로 `join`메서드가 없어도 문제 없을 것 같습니다

2023-01-26 11:17 UTC, rrgks6221 commented on src/guards/member-major.guard.spec.ts
> +        }).toThrowError('Development, Design major 유저만 접근 가능합니다.');
오 faker 에 그런것도 있었네요.
하지만 여기서 사용하게되면 어떤 랜덤한 값이 뽑혔을 때 분기처리를 테스트코드 내에서 해야할거같아서 부적절할거같아요
테스트코드에서는 최대한 if 문 같은 논리적인 코드를 피해야한다고 본 기억이 있어서 혹시 arrayElements 를 사용해서 깔끔하게 짤 수 있는 방법 있으면 공유해주시면 감사하겠습니다.

2023-01-26 11:17 UTC, rrgks6221 commented on src/guards/member-major.guard.ts
> + */
넵 좋은 부분인거같아요 추가로 setMetadata 와 함께 쓰여야하는 guard, interceptor 에도 추가해놓도록 할게요

2023-01-26 11:17 UTC, rrgks6221 commented on src/guards/member-major.guard.ts
> +    }
변수명의 allowMemberMajors 가 겹쳐서 생긴 문제같은데 실제 includes 를 사용하는 array 는 allowMemberMajors 이고
allowMemberMajorsStr 은 클라이언트에게 보여주기 위한 메시지를 위해 가공한 문자열입니다.
allowMemberMajors => [0, 1];
allowMemberMajorsStr => Development, Design

2023-01-26 11:17 UTC, rrgks6221 commented on src/guards/member-major.guard.ts
> +    return true;
넵넵 기획적인 요소가 불분명해서 우선 열려있게 만들어놨습니다.

2023-01-26 11:17 UTC, rrgks6221 commented on src/guards/own-member.guard.spec.ts
> +    });
저도 이부분 아직 정확하게 아는건 아니라 알게되면 공유해드릴게요

2023-01-26 11:17 UTC, rrgks6221 commented on test/mock/mock-libs.ts
> +export const mockReflector = {
5000줄 pr 에 있었어요...

2023-01-26 11:17 UTC, rrgks6221 commented on src/guards/member-status.guard.ts
> +    }
https://github.com/the-pool/the-pool-api/pull/82#discussion_r1087707258

2023-01-26 11:18 UTC, rrgks6221 commented
이거 draft 처리 후 코멘트 반영사항 처리 + develop branch 와의 conflict 해결 후 다시 열도록 할게요

2023-01-26 11:52 UTC, RokwonK commented on src/guards/member-major.guard.ts
> +    }
앗앗 확인했습니다 감사합니다!

2023-01-29 08:09 UTC, RokwonK approved these changes
Gooood!!

2023-01-31 13:07 UTC, subroooo approved these changes
고생하셨슴다! 
it.each + arrayElements 관련 코멘트 추가했으니 확인 부탁드립니다~

2023-01-31 13:07 UTC, subroooo commented on src/guards/member-major.guard.spec.ts
> +        }).toThrowError('Development, Design major 유저만 접근 가능합니다.');
```suggestion
   describe('test', () => {
  it.each([0, 1, 2])('성공케이스 - count: %s', (count) => {
    majorId = faker.helpers.arrayElements(
      [MajorId.Development, MajorId.Design],
      count,
    );
    allowMemberMajors = [majorId];

    mockReflector.get.mockReturnValue(allowMemberMajors);

    member.majorId = majorId;
    mockRequest.user = member;

    expect(memberMajorGuard.canActivate(mockContext)).toBeTruthy();
  });
});
```
약간 요런 느낌을 말씀드린거였슴다 ㅎㅎ

2023-02-04 09:04 UTC, rrgks6221 commented
> 고생하셨슴다! it.each + arrayElements 관련 코멘트 추가했으니 확인 부탁드립니다~

상당히 좋은 방법인거같은데 이번 작업때는 참고만 하고 다음 테스트코드짤 때 적용해볼게요

2023-02-04 09:05 UTC, merged